[package]
name = "rgit"
version = "0.0.1"
authors = ["Macklan Weinstein <wolfgangwazzlestrauss@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
clap = "3.0.0-beta.2"
sha3 = "0.9.1"

[dev-dependencies]
tempfile = "3.1.0"
