# Project task runner. See https://github.com/sagiegurari/cargo-make for info.

[tasks.all]
dependencies = [
    "format",
    "build",
    "test"
]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]
