# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: build

on:
  push:
    branches:
      - develop
      - feature/*
      - master

jobs:
  # Lint Rust code.
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code repository checkout
        uses: actions/checkout@v2
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      # Does not use dependency caching since Clippy may not work correctly with
      # cached dependencies. See
      # https://github.com/rust-lang/rust-clippy/issues/4612 for details.
      - name: Run Rust code linters
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  # Run Rust tests on code.
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code repository checkout
        uses: actions/checkout@v2
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download dependency cache
        uses: swatinem/rust-cache@v1
      - name: Run Rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  # Run Rust tests on code.
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Code repository checkout
        uses: actions/checkout@v2
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download dependency cache
        uses: swatinem/rust-cache@v1
      - name: Run test code coverage
        uses: actions-rs/tarpaulin@v0.1
